import Providers from "@/app/Providers";
import Header from "../components/Header/Header";
import "../styles/globals.css";
import { ServerThemeProvider } from "next-themes";

export const metadata = {
  title: "News App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className='bg-gray-100 dark:bg-zinc-900 transition-all duration-700'>
        <Providers>
          <Header />
          <div className='max-w-6xl mx-auto'>{children}</div>
        </Providers>
      </body>
    </html>
  );
}
